window.bootstrap = require("bootstrap");
import "@/styles/main.scss";
// import "bootstrap";
// import "@/js/swiper";
// import "@/js/modules/questions";
// import "@/js/modules/animationOnScroll";
import "@/js/modules/lozad";
import "@/js/modules/hamburgerLinks";
// import "@/js/modules/toc";
// import "@/js/modules/advertisingDisclousureInsert";
// import "@/js/modules/tooltips";
// import "@/js/modules/reviewsSlider";
// import "@/js/modules/checkSmartBanner";
// import "@/js/modules/sidebarNegativeOffset";
// import "@/js/modules/contactModal";
// import "@/js/modules/redirectToApp";
// import "@/js/modules/starsRating";
// import "@/js/modules/customSelect";
// import "@/js/modules/communitySlider";
// import "@/js/modules/formLoader";
// import "@/js/modules/swiperGridPosts";
// import "@/js/modules/customHref";
// import "@/js/modules/replaceInlineSvg";
// import "@/js/modules/unifyCardsHeight";
// import "@/js/our-form";