window.bootstrap = require('bootstrap');
import "@/styles/main.scss";
// import "bootstrap";
import "@/js/swiper";
import "@/js/lozad";
import "@/js/questions";
import "@/js/preloader";
import "@/js/hamburgerLinks";
import "@/js/toc";
import "@/js/tooltips";
import "@/js/reviewsSlider";
// import "@/js/checkSmartBanner";
import "@/js/sidebarNegativeOffset";
